name: review-gator
adopt-info: review-gator
base: core20
summary: Helpful utility to render merge proposals as HTML
description: |
  Helpful utility to render merge proposals from launchpad and pull
  requests from github as HTML

  review-gator.py --help # to see all available options
  review-gator.py --config branches.yaml # branches must be under your home directory
  export GITHUB_TOKEN=%GITHUBAPITOKEN; review-gator.py --config branches.yaml # if you have any github repos configured
  review-gator.py --config branches.yaml --config-skeleton # Output sample config skeleton
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

grade: stable
confinement: strict

apps:
  review-gator:
    command: bin/python3 $SNAP/bin/review-gator
    command-chain:
      - bin/snapcraft-preload # Fixes multiprocessing python module
    plugs:
      - network
      - home

parts:
  review-gator:
    plugin: python
    source: .
    python-packages:
      - pip>=20
      - setuptools>=40
      - setuptools-rust
      - wheel
    source-type: git
    build-packages:
      - python3-dev
    build-environment:
      - C_INCLUDE_PATH: /usr/include/python3.8/
    stage-packages:
      - git
      - rustc
      - libpython3-stdlib
      - libpython3.8-stdlib
      - libpython3.8-minimal
      - python3
      - python3-distutils
      - python3-lib2to3
      - python3-minimal
      - python3-pip
      - python3-pkg-resources
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - python3.8-minimal
    override-pull: |
      snapcraftctl pull
      DATE="$(date +%Y.%m.%d)"
      GIT="$(git rev-parse --short HEAD)"
      snapcraftctl set-version "${DATE}+git${GIT}"

  snapcraft-preload:
    source: https://github.com/diddledan/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
    stage-packages:
      - on amd64:
          - lib32stdc++6

